### ISSUE TITLE
Issues about remote sensing image dehazing

### ISSUE THREAD

**Issue by NothingToSay99** [IDKiro/DehazeFormer#1]
Great works！
and whether you test the dehazing model on other remote sensing images except the ones in your RESHAZE datasets

**Comment by IDKiro** [comment]
Good question.
To be honest, both RESIDE and RS-Haze trained models (DehazeFormer and baselines) are far less valid on real hazy images than on synthetic hazy images (especially the RESIDE outdoor).
This is mainly because the actual degradation process is much more complicated than I=Jt+(1-A)t.
In addition, the sensor model of the satellite and the data pre-processing may also have a non-negligible effect on the dehazing performance.
Of course, RS-Haze is still more realistic than the synthetic hazy images from previous works, and the models trained on it are able to achieve visible dehazing effect on real hazy images.

**Comment by NothingToSay99** [comment]
> Good question. To be honest, both RESIDE and RS-Haze trained models (DehazeFormer and baselines) are far less valid on real hazy images than on synthetic hazy images (especially the RESIDE outdoor). This is mainly because the actual degradation process is much more complicated than I=Jt+A(1-t). In addition, the sensor model of the satellite and the data pre-processing may also have a non-negligible effect on the dehazing performance. Of course, RS-Haze is still more realistic than the synthetic hazy images from previous works, and the models trained on it are able to achieve visible dehazing effect on real hazy images.

Yeeeeeeep....
I have tested on another remote sensing images, as you said, the results is not good. So....there may be a gap between realistic and synthetic data. 
And will you share your code which process the synthetic hazy images later？

**Comment by IDKiro** [comment]
I am so sorry.
The code for the data set synthesis was written by another author, who will be doing further research in the near future, so there is no plan for this until he is done.
I think it is really key to increase the realism of the synthesis process, you can try to investigate.

**Comment by IDKiro** [comment]
If you have any other questions, please send me an email, I'll close this issue for now.

**Comment by NothingToSay99** [comment]
> If you have any other questions, please send me an email, I'll close this issue for now.

ok, fine! Thanks for your reply and your excellent work.
